
[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "workspace"
version = "0.1.0"
description = ""
authors = [{name = "Troy Evans", email = "41166009-SimpleNow@users.noreply.replit.com"}]
readme = "README.md"
requires-python = ">=3.11"
